### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by mttdvp** [bbc/audio-offset-finder#5]
On a fresh ubuntu/trusty64 VM, installation failed. I don't understand why but maybe the developer can take a look at this. I am pasting the output from my terminal below. Thanks. 

vagrant@vagrant-ubuntu-trusty-64:~$ pip install audio-offset-finder
Downloading/unpacking audio-offset-finder
  Downloading audio-offset-finder-0.3.0.tar.gz
  Running setup.py (path:/tmp/pip_build_vagrant/audio-offset-finder/setup.py) egg_info for package audio-offset-finder
    
Downloading/unpacking scipy>=0.12.0 (from audio-offset-finder)
  Downloading scipy-1.0.0.tar.gz (15.2MB): 15.2MB downloaded
  Running setup.py (path:/tmp/pip_build_vagrant/scipy/setup.py) egg_info for package scipy
    Running from numpy source directory.
    /tmp/easy_install-0OdlvR/numpy-1.14.0/setup.py:369: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    /tmp/easy_install-0OdlvR/numpy-1.14.0/numpy/distutils/system_info.py:624: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    /tmp/easy_install-0OdlvR/numpy-1.14.0/numpy/distutils/system_info.py:624: UserWarning:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
      self.calc_info()
    /tmp/easy_install-0OdlvR/numpy-1.14.0/numpy/distutils/system_info.py:624: UserWarning:
        Blas (http://www.netlib.org/blas/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [blas_src]) or by setting
        the BLAS_SRC environment variable.
      self.calc_info()
    /bin/sh: 1: svnversion: not found
    /bin/sh: 1: svnversion: not found
    /tmp/easy_install-0OdlvR/numpy-1.14.0/numpy/distutils/system_info.py:624: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    /tmp/easy_install-0OdlvR/numpy-1.14.0/numpy/distutils/system_info.py:624: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    non-existing path in 'numpy/distutils': 'site.cfg'
    Could not locate executable gfortran
    Could not locate executable f95
    Could not locate executable ifort
    Could not locate executable ifc
    Could not locate executable lf95
    Could not locate executable pgfortran
    Could not locate executable f90
    Could not locate executable f77
    Could not locate executable fort
    Could not locate executable efort
    Could not locate executable efc
    Could not locate executable g77
    Could not locate executable g95
    Could not locate executable pathf95
    Could not locate executable nagfor
    don't know how to compile Fortran code on platform 'posix'
    _configtest.c:1:5: warning: conflicting types for built-in function ‘exp’ [enabled by default]
     int exp (void);
         ^
    _configtest.o: In function `main':
    /tmp/easy_install-0OdlvR/numpy-1.14.0/_configtest.c:6: undefined reference to `exp'
    collect2: error: ld returned 1 exit status
    _configtest.o: In function `main':
    /tmp/easy_install-0OdlvR/numpy-1.14.0/_configtest.c:6: undefined reference to `exp'
    collect2: error: ld returned 1 exit status
    _configtest.c:1:5: warning: conflicting types for built-in function ‘exp’ [enabled by default]
     int exp (void);
         ^
    _configtest.c:1:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    _configtest.c:1:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_vagrant/scipy/setup.py", line 418, in <module>
        setup_package()
      File "/tmp/pip_build_vagrant/scipy/setup.py", line 414, in setup_package
        setup(**metadata)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs
        replace_conflicting=True
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 858, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 870, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 314, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 616, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 646, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 834, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1040, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1025, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 50, in run_setup
        lambda: execfile(
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 100, in run
        return func()
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 52, in <lambda>
        {'__file__':setup_script, '__name__':'__main__'}
      File "setup.py", line 394, in <module>
        # higher up in this file.
      File "setup.py", line 386, in setup_package
        run_build = True
      File "/tmp/easy_install-0OdlvR/numpy-1.14.0/numpy/distutils/core.py", line 169, in setup
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 177, in run
        self.run_command("egg_info")
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/easy_install-0OdlvR/numpy-1.14.0/numpy/distutils/command/egg_info.py", line 26, in run
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/easy_install-0OdlvR/numpy-1.14.0/numpy/distutils/command/build_src.py", line 148, in run
      File "/tmp/easy_install-0OdlvR/numpy-1.14.0/numpy/distutils/command/build_src.py", line 165, in build_sources
      File "/tmp/easy_install-0OdlvR/numpy-1.14.0/numpy/distutils/command/build_src.py", line 324, in build_extension_sources
      File "/tmp/easy_install-0OdlvR/numpy-1.14.0/numpy/distutils/command/build_src.py", line 377, in generate_sources
      File "numpy/core/setup.py", line 422, in generate_config_h
    
      File "numpy/core/setup.py", line 48, in check_types
        Programming Language :: Python :: 3.3
      File "numpy/core/setup.py", line 281, in check_types
        `setup.py test` is not supported.  Use one of the following
    SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.
    Complete output from command python setup.py egg_info:
    Running from numpy source directory.

/tmp/easy_install-0OdlvR/numpy-1.14.0/setup.py:369: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates

  run_build = parse_setuppy_commands()

/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'

  warnings.warn(msg)

/tmp/easy_install-0OdlvR/numpy-1.14.0/numpy/distutils/system_info.py:624: UserWarning:

    Atlas (http://math-atlas.sourceforge.net/) libraries not found.

    Directories to search for the libraries can be specified in the

    numpy/distutils/site.cfg file (section [atlas]) or by setting

    the ATLAS environment variable.

  self.calc_info()

/tmp/easy_install-0OdlvR/numpy-1.14.0/numpy/distutils/system_info.py:624: UserWarning:

    Blas (http://www.netlib.org/blas/) libraries not found.

    Directories to search for the libraries can be specified in the

    numpy/distutils/site.cfg file (section [blas]) or by setting

    the BLAS environment variable.

  self.calc_info()

/tmp/easy_install-0OdlvR/numpy-1.14.0/numpy/distutils/system_info.py:624: UserWarning:

    Blas (http://www.netlib.org/blas/) sources not found.

    Directories to search for the sources can be specified in the

    numpy/distutils/site.cfg file (section [blas_src]) or by setting

    the BLAS_SRC environment variable.

  self.calc_info()

/bin/sh: 1: svnversion: not found

/bin/sh: 1: svnversion: not found

/tmp/easy_install-0OdlvR/numpy-1.14.0/numpy/distutils/system_info.py:624: UserWarning:

    Lapack (http://www.netlib.org/lapack/) libraries not found.

    Directories to search for the libraries can be specified in the

    numpy/distutils/site.cfg file (section [lapack]) or by setting

    the LAPACK environment variable.

  self.calc_info()

/tmp/easy_install-0OdlvR/numpy-1.14.0/numpy/distutils/system_info.py:624: UserWarning:

    Lapack (http://www.netlib.org/lapack/) sources not found.

    Directories to search for the sources can be specified in the

    numpy/distutils/site.cfg file (section [lapack_src]) or by setting

    the LAPACK_SRC environment variable.

  self.calc_info()

/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'define_macros'

  warnings.warn(msg)

non-existing path in 'numpy/distutils': 'site.cfg'

Could not locate executable gfortran

Could not locate executable f95

Could not locate executable ifort

Could not locate executable ifc

Could not locate executable lf95

Could not locate executable pgfortran

Could not locate executable f90

Could not locate executable f77

Could not locate executable fort

Could not locate executable efort

Could not locate executable efc

Could not locate executable g77

Could not locate executable g95

Could not locate executable pathf95

Could not locate executable nagfor

don't know how to compile Fortran code on platform 'posix'

_configtest.c:1:5: warning: conflicting types for built-in function ‘exp’ [enabled by default]

 int exp (void);

     ^

_configtest.o: In function `main':

/tmp/easy_install-0OdlvR/numpy-1.14.0/_configtest.c:6: undefined reference to `exp'

collect2: error: ld returned 1 exit status

_configtest.o: In function `main':

/tmp/easy_install-0OdlvR/numpy-1.14.0/_configtest.c:6: undefined reference to `exp'

collect2: error: ld returned 1 exit status

_configtest.c:1:5: warning: conflicting types for built-in function ‘exp’ [enabled by default]

 int exp (void);

     ^

_configtest.c:1:20: fatal error: Python.h: No such file or directory

 #include <Python.h>

                    ^

compilation terminated.

_configtest.c:1:20: fatal error: Python.h: No such file or directory

 #include <Python.h>

                    ^

compilation terminated.

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_vagrant/scipy/setup.py", line 418, in <module>

    setup_package()

  File "/tmp/pip_build_vagrant/scipy/setup.py", line 414, in setup_package

    setup(**metadata)

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 239, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs

    replace_conflicting=True

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve

    dist = best[req.key] = env.best_match(req, ws, installer)

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 858, in best_match

    return self.obtain(req, installer) # try and download/install

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 870, in obtain

    return installer(requirement)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 314, in fetch_build_egg

    return cmd.easy_install(req)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 616, in easy_install

    return self.install_item(spec, dist.location, tmpdir, deps)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 646, in install_item

    dists = self.install_eggs(spec, download, tmpdir)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 834, in install_eggs

    return self.build_and_install(setup_script, setup_base)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1040, in build_and_install

    self.run_setup(setup_script, setup_base, args)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1025, in run_setup

    run_setup(setup_script, args)

  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 50, in run_setup

    lambda: execfile(

  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 100, in run

    return func()

  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 52, in <lambda>

    {'__file__':setup_script, '__name__':'__main__'}

  File "setup.py", line 394, in <module>

    # higher up in this file.

  File "setup.py", line 386, in setup_package

    run_build = True

  File "/tmp/easy_install-0OdlvR/numpy-1.14.0/numpy/distutils/core.py", line 169, in setup

  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup

    dist.run_commands()

  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 177, in run

    self.run_command("egg_info")

  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/tmp/easy_install-0OdlvR/numpy-1.14.0/numpy/distutils/command/egg_info.py", line 26, in run

  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/tmp/easy_install-0OdlvR/numpy-1.14.0/numpy/distutils/command/build_src.py", line 148, in run

  File "/tmp/easy_install-0OdlvR/numpy-1.14.0/numpy/distutils/command/build_src.py", line 165, in build_sources

  File "/tmp/easy_install-0OdlvR/numpy-1.14.0/numpy/distutils/command/build_src.py", line 324, in build_extension_sources

  File "/tmp/easy_install-0OdlvR/numpy-1.14.0/numpy/distutils/command/build_src.py", line 377, in generate_sources

  File "numpy/core/setup.py", line 422, in generate_config_h

  File "numpy/core/setup.py", line 48, in check_types

    Programming Language :: Python :: 3.3

  File "numpy/core/setup.py", line 281, in check_types

    `setup.py test` is not supported.  Use one of the following

SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_vagrant/scipy
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 235, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 72: ordinal not in range(128)

**Comment by smidm** [comment]
The missing `Python.h` error is due to missing ubuntu package `python-dev`.
